# Generated by Django 4.2.11 on 2024-05-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_author_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='main.category'),
        ),
    ]
